language: go

go:
  - "1.x"

services:
  - docker

script:
  - make docker
  - make docker-test
  - if [ "$TRAVIS_BRANCH" == "master" ]; then 
      make docker-login ;
      make docker-publish ; 
    fi
